# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib junctionsrs, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_junctionsrs_wrappers", use_symbols = TRUE, package_name = "junctionsrs")

#' @usage NULL
#' @useDynLib junctionsrs, .registration = TRUE
NULL

#' Detect junctions from a JSON array of projected road centrelines.
#'
#' @param roads_json A JSON array of `{id, coordinates, level}` roads.
#' @param buffer_m Polygon half-width in projected metres.
#' @param min_arms Minimum contributing-road count.
#' @param cluster_distance_m Candidate-node merge tolerance in metres.
#' @return A JSON array of deterministic junctions.
#' @export
junctions_json <- function(roads_json, buffer_m, min_arms, cluster_distance_m) .Call(wrap__junctions_json, roads_json, buffer_m, min_arms, cluster_distance_m)

# nolint end
